# Generated by Django 4.1.2 on 2023-07-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_data_manager', '0003_mtgstore_mtgstoreprice_mtgcard_prices_additionalstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtgstoreprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
