# Generated by Django 4.1.2 on 2023-08-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comm_manager', '0003_chatuser_chatmembership_chat_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm_manager.chat')),
                ('chat_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comm_manager.chatuser')),
            ],
        ),
    ]
